version: '3'

services:
  datab:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    # ports:
    #   - "3307:3306"
    expose:
      - "3306"
    networks:
      employee:
        ipv4_address: 172.21.0.2

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    ports: 
        - "8080:3000"
    depends_on:
        - datab
    environment:
      DB_USER: user
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
    networks:
      employee:
        ipv4_address: 172.21.0.3

networks:
  employee:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16
         gateway: 172.21.0.1